// /studentdb.js
export const studentsData = [
  // {
  //   seatNumber: "2024001",
  //   elnum: "100",
  //   name: "Yash Patel Admin of Thakur",
  //   class: "Computer Engineering",
  //   semester: "6th Semester",
  //   percentage: 100,
  //   remark: "FIRST CLASS DIST.",
  //   subjects: [
  //     { name: "MANAGEMENT", marks: 100, total: 100 },
  //     { name: "PROGRAMMING WITH PYTHON", marks: 100, total: 100 },
  //     { name: "MOBILE APPLICATION DEVELOPMENT", marks: 100, total: 100 },
  //     {
  //       name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
  //       marks: 100,
  //       total: 100,
  //     },
  //     {
  //       name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
  //       marks: 100,
  //       total: 100,
  //     },
  //   ],
  //   pdfPath: "/results/1.pdf",
  // },
  {
    //number 1
    seatNumber: "153091",
    elnum: "2116350091 ",
    name: "KOTI HEMANT MADHUKAR",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 75.06,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 75, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 66, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 55, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 70,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 77,
        total: 100,
      },
    ],
    pdfPath: "/results/1.pdf",
  },
  {
    //number 2
    seatNumber: "153092",
    elnum: "2216350002",
    name: "BARI YUG NILESH",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 71.29,
    remark: "FIRST CLASS",
    subjects: [
      { name: "MANAGEMENT", marks: 75, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 66, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 55, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 70,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 77,
        total: 100,
      },
    ],
    pdfPath: "/results/2.pdf",
  },
  {
    //number 3
    seatNumber: "	153093 ",
    elnum: "2216350005 ",
    name: "	KHAN FAIZAN SAFRUDDIN",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 67.65,
    remark: "FIRST CLASS",
    subjects: [
      { name: "MANAGEMENT", marks: 65, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 57, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 54, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 57,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 64,
        total: 100,
      },
    ],
    pdfPath: "/results/3.pdf",
  },
  {
    //number 4
    seatNumber: "	153094 ",
    elnum: "2216350006 ",
    name: "	VISHWAKARMA ABHAY RAMBHAROSE",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 78.24,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 66, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 74, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 65, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 77,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 70,
        total: 100,
      },
    ],
    pdfPath: "/results/4.pdf",
  },
  {
    //number 5
    seatNumber: "	153095 ",
    elnum: "2216350009 ",
    name: "	PATIL HONEY VIRAJ",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 76.35,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 66, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 86, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 61, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 44,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 82,
        total: 100,
      },
    ],
    pdfPath: "/results/5.pdf",
  },
  {
    //number 6
    seatNumber: "	153096 ",
    elnum: "2216350010	 ",
    name: "	KHAN NOOR BEE ANWAR",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 75.0,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 58, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 65, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 64, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 67,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 76,
        total: 100,
      },
    ],
    pdfPath: "/results/6.pdf",
  },
  {
    //number 7
    seatNumber: "	153097 ",
    elnum: "2216350011	 ",
    name: "	SURABHI MANGALKUMAR GHARAT",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 81.29,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 72, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 79, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 79, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 75,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 78,
        total: 100,
      },
    ],
    pdfPath: "/results/7.pdf",
  },
  {
    //number 8
    seatNumber: "	153063 ",
    elnum: "2216350012	 ",
    name: "		SHAIKH MOHD ZAKI JAVED",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 66.82,
    remark: "FIRST CLASS",
    subjects: [
      { name: "MANAGEMENT", marks: 64, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 51, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 50, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 67,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 54,
        total: 100,
      },
    ],
    pdfPath: "/results/8.pdf",
  },
  {
    //number 9
    seatNumber: "	153099 ",
    elnum: "	2216350013	 ",
    name: "	MAYEKAR YASH SANTOSH",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 71.41,
    remark: "FIRST CLASS",
    subjects: [
      { name: "MANAGEMENT", marks: 68, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 59, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 55, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 64,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 63,
        total: 100,
      },
    ],
    pdfPath: "/results/9.pdf",
  },
  {
    //number 10
    seatNumber: "	153100 ",
    elnum: "	2216350015	 ",
    name: "NEHA ASHOK SHINDE",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 82.71,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 69, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 85, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 79, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 77,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 80,
        total: 100,
      },
    ],
    pdfPath: "/results/10.pdf",
  },
  {
    //number 11
    seatNumber: "	153102 ",
    elnum: "	2216350017	 ",
    name: "SHAIKH SAYMA GULJAR",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 78.12,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 72, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 75, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 65, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 75,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 73,
        total: 100,
      },
    ],
    pdfPath: "/results/11.pdf",
  },
  {
    //number 12
    seatNumber: "	153103 ",
    elnum: "	2216350018	 ",
    name: "KHAN SOLEHA ABDUL AZIZ",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 76.82,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 63, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 61, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 62, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 63,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 81,
        total: 100,
      },
    ],
    pdfPath: "/results/12.pdf",
  },
  {
    //number 13
    seatNumber: "	153104 ",
    elnum: "	2216350019	 ",
    name: "	SHAIKH OWAIS ASLAM",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 80.94,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 66, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 87, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 70, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 66,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 84,
        total: 100,
      },
    ],
    pdfPath: "/results/13.pdf",
  },
  {
    //number 14
    seatNumber: "	153105 ",
    elnum: "	2216350021	 ",
    name: "	SHAIKH ALIHASAN GANI",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 82.24,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 67, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 90, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 78, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 66,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 82,
        total: 100,
      },
    ],
    pdfPath: "/results/14.pdf",
  },
  {
    //number 15
    seatNumber: "	153106 ",
    elnum: "	2216350022	 ",
    name: "	SALMAN RAMZAN TAMBOLI",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 84.71,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 80, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 85, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 74, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 78,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 82,
        total: 100,
      },
    ],
    pdfPath: "/results/15.pdf",
  },
  {
    //number 16
    seatNumber: "	153107 ",
    elnum: "	2216350023	 ",
    name: "	PARHAD PRIYANKA SURESH",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 75.77,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 56, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 71, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 64, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 64,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 74,
        total: 100,
      },
    ],
    pdfPath: "/results/16.pdf",
  },
  {
    //number 17
    seatNumber: "	153108 ",
    elnum: "	2216350024	 ",
    name: "WAGHMODE SNEHAL DHANAJI",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 79.06,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 66, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 77, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 74, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 72,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 74,
        total: 100,
      },
    ],
    pdfPath: "/results/17.pdf",
  },
  {
    //number 18
    seatNumber: "	153109 ",
    elnum: "	2216350025	 ",
    name: "	SINGH CHANDAN HARENDRA",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 75.29,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 67, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 64, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 61, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 68,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 76,
        total: 100,
      },
    ],
    pdfPath: "/results/18.pdf",
  },
  {
    //number 19
    seatNumber: "	153110 ",
    elnum: "	2216350026	 ",
    name: "PATEL YASH OMPRAKASH",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 83.18,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 76, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 91, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 73, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 70,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 78,
        total: 100,
      },
    ],
    pdfPath: "/results/19.pdf",
  },
  {
    //number 20
    seatNumber: "	153111",
    elnum: "	2216350027	 ",
    name: "KHAN SAMA ABDULAJIJ",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 75.0,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 67, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 54, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 60, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 68,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 74,
        total: 100,
      },
    ],
    pdfPath: "/results/20.pdf",
  },
  {
    //number 21
    seatNumber: "	153112 ",
    elnum: "	2216350028	 ",
    name: "	SAYYED SAMEER SHARIF",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 73.18,
    remark: "FIRST CLASS",
    subjects: [
      { name: "MANAGEMENT", marks: 72, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 52, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 55, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 74,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 72,
        total: 100,
      },
    ],
    pdfPath: "/results/21.pdf",
  },
  {
    //number 22
    seatNumber: "	153113 ",
    elnum: "	2216350029	 ",
    name: "	WADE ARYA SANTOSH",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 90.0,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 82, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 90, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 84, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 91,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 97,
        total: 100,
      },
    ],
    pdfPath: "/results/22.pdf",
  },
  {
    //number 23
    seatNumber: "	153114 ",
    elnum: "	2216350030	 ",
    name: "	PIMPLE GARGI MANOJ",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 82.24,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 68, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 82, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 81, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 74,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 79,
        total: 100,
      },
    ],
    pdfPath: "/results/23.pdf",
  },
  {
    //number 24
    seatNumber: "	153115 ",
    elnum: "	2216350031	 ",
    name: "RAIEN SOHEL AKBAR ALI",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 78.59,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 63, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 88, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 70, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 64,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 82,
        total: 100,
      },
    ],
    pdfPath: "/results/24.pdf",
  },
  {
    //number 25
    seatNumber: "	153178 ",
    elnum: "	2216350032	 ",
    name: "	PEDNEKAR KAJOL SUNIL",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 75.18,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 77, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 60, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 59, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 88,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 55,
        total: 100,
      },
    ],
    pdfPath: "/results/25.pdf",
  },
  {
    //number 26
    seatNumber: "	153117 ",
    elnum: "	2216350033	 ",
    name: "PASWAN SURAJ VIDYANAND",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage:74.12,
    remark: "FIRST CLASS",
    subjects: [
      { name: "MANAGEMENT", marks: 66, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 66, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 62, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 66,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 75,
        total: 100,
      },
    ],
    pdfPath: "/results/26.pdf",
  },
  {
    //number 27
    seatNumber: "	153118 ",
    elnum: "	2216350034	 ",
    name: "	SANKHE MANTHAN SANTOSH",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 75.88,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 84, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 58, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 54, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 78,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 67,
        total: 100,
      },
    ],
    pdfPath: "/results/27.pdf",
  },
  {
    //number 28
    seatNumber: "	153119",
    elnum: "	2216350035	 ",
    name: "	CHAMPANERI SUJAL NARENDRA",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 81.06,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 77, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 80, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 67, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 81,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 79,
        total: 100,
      },
    ],
    pdfPath: "/results/28.pdf",
  },
  {
    //number 29
    seatNumber: "	153120",
    elnum: "	2216350037	 ",
    name: "	TARE PARAG RAMESH",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage:69.88,
    remark: "FIRST CLASS",
    subjects: [
      { name: "MANAGEMENT", marks: 55, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 64, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 57, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 70,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 60,
        total: 100,
      },
    ],
    pdfPath: "/results/29.pdf",
  },
  {
    //number 30
    seatNumber: "	153121",
    elnum: "	2216350038	 ",
    name: "MALI VIDHI PRAKASH",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage:79.41,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 66, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 86, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 71, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 74,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 72,
        total: 100,
      },
    ],
    pdfPath: "/results/30.pdf",
  },
  {
    //number 31
    seatNumber: "	153122",
    elnum: "	2216350039	 ",
    name: "	SOPARKAR MOHAMMED SHARIB MAHEMUD",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage:69.65	,
    remark: "FIRST CLASS",
    subjects: [
      { name: "MANAGEMENT", marks: 57, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 66, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 53, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 53,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 70,
        total: 100,
      },
    ],
    pdfPath: "/results/31.pdf",
  },
  {
    //number 32
    seatNumber: "	153123",
    elnum: "	2216350040	 ",
    name: "	SANKHE ISHA NAYAN",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage:82.59,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 68, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 82, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 73, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 79,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 83,
        total: 100,
      },
    ],
    pdfPath: "/results/32.pdf",
  },
  {
    //number 33
    seatNumber: "	153124",
    elnum: "	2216350042	 ",
    name: "	MISHRA ADITYA MANOJ",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage:71.88,
    remark: "FIRST CLASS",
    subjects: [
      { name: "MANAGEMENT", marks: 61, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 59, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 60, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 74,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 67,
        total: 100,
      },
    ],
    pdfPath: "/results/33.pdf",
  },
  {
    //number 34
    seatNumber: "	153125",
    elnum: "	2216350044	 ",
    name: "	PATIL DHRUV SANDESH",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage:76.24	,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 71, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 65, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 58, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 83,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 63,
        total: 100,
      },
    ],
    pdfPath: "/results/34.pdf",
  },
  {
    //number 35
    seatNumber: "	153126",
    elnum: "	2216350045	 ",
    name: "	RAUT SHARVIL PRASHANT",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage:80.94,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 80, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 82, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 60, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 84,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 75,
        total: 100,
      },
    ],
    pdfPath: "/results/35.pdf",
  },
  {
    //number 36
    seatNumber: "	153127",
    elnum: "	2216350048 ",
    name: "	MAHAJAN SIDDHANT VIJAY",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage:75.41,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 63, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 71, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 64, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 75,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 71,
        total: 100,
      },
    ],
    pdfPath: "/results/36.pdf",
  },
  {
    //number 37
    seatNumber: "	153128",
    elnum: "	2216350050",
    name: "PATIL VINI SURESH",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage:83.88,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 84, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 86, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 77, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 77,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 84,
        total: 100,
      },
    ],
    pdfPath: "/results/37.pdf",
  },
  {
    //number 38
    seatNumber: "	153129",
    elnum: "	2216350051",
    name: "	KINI VED NARAYAN",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage:77.77,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 73, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 77, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 73, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 62,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 79,
        total: 100,
      },
    ],
    pdfPath: "/results/38.pdf",
  },
  {
    //number 39
    seatNumber: "	153130",
    elnum: "	2216350052",
    name: "GHARAT KUNAL KESHAV",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage:75.00,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 66, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 71, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 68, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 57,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 81,
        total: 100,
      },
    ],
    pdfPath: "/results/39.pdf",
  },
  {
    //number 40
    seatNumber: "	153131",
    elnum: "	2216350053",
    name: "	ANSARI MD SHAHVEZ MD IBRAHIM",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage:79.77,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 75, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 74, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 72, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 67,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 92,
        total: 100,
      },
    ],
    pdfPath: "/results/40.pdf",
  },
  {
    //number 41
    seatNumber: "	153132",
    elnum: "	2216350054",
    name: "	JADHAV PRATHAMESH SUNIL",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage:79.53,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 66, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 85, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 76, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 62,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 92,
        total: 100,
      },
    ],
    pdfPath: "/results/41.pdf",
  },
  {
    //number 42
    seatNumber: "	153133",
    elnum: "	2216350055",
    name: "		ADITYA AVINASH HANDE",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage:82.12,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 77, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 85, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 80, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 77,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 75,
        total: 100,
      },
    ],
    pdfPath: "/results/42.pdf",
  },
  {
    //number 43
    seatNumber: "	153134",
    elnum: "	2216350056",
    name: "	SHAIKH MOHAMMED YASIN JAMALUDDIN",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage:77.41,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 76, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 52, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 77, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 66,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 79,
        total: 100,
      },
    ],
    pdfPath: "/results/43.pdf",
  },
  {
    //number 44
    seatNumber: "	153135",
    elnum: "	2216350057",
    name: "SHAIKH MOHD HUSSAIN MOHD YUSUF",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 85.06,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 74, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 87, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 76, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 86,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 78,
        total: 100,
      },
    ],
    pdfPath: "/results/44.pdf",
  },
  {
    //number 45
    seatNumber: "	153140",
    elnum: "23112500142",
    name: "	SHAIKH ABDURRAZZAQ UBAIDULLAH",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 77.65,
    remark: "FIRST CLASS DIST.",
    subjects: [
      { name: "MANAGEMENT", marks: 64, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 69, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 67, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 79,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 87,
        total: 100,
      },
    ],
    pdfPath: "/results/45.pdf",
  },
  {
    //number 46
    seatNumber: "	153141",
    elnum: "23112500144",
    name: "		SHAIKH ALFIYA SAJID",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 71.53,
    remark: "FIRST CLASS",
    subjects: [
      { name: "MANAGEMENT", marks: 83, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 53, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 56, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 58,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 55,
        total: 100,
      },
    ],
    pdfPath: "/results/46.pdf",
  },
{
    //number 47
    seatNumber: "	153142",
    elnum: "23112500145",
    name: "	SHAH REHAN DAUD",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 66.47	,
    remark: "FIRST CLASS",
    subjects: [
      { name: "MANAGEMENT", marks: 69, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 58, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 45, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 57,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 55,
        total: 100,
      },
    ],
    pdfPath: "/results/47.pdf",
  },
{
    //number 48
    seatNumber: "	153143",
    elnum: "23112500147",
    name: "	SHAIKH AZHAN REHAN",
    class: "Computer Engineering",
    semester: "6th Semester",
    percentage: 70.59,
    remark: "FIRST CLASS",
    subjects: [
      { name: "MANAGEMENT", marks: 75, total: 100 },
      { name: "PROGRAMMING WITH PYTHON", marks: 60, total: 100 },
      { name: "MOBILE APPLICATION DEVELOPMENT", marks: 53, total: 100 },
      {
        name: "EMERGING TRENDS IN COMPUTER AND INFORMATION TECHNOLGY",
        marks: 58,
        total: 100,
      },
      {
        name: "WEB BASED APPLICATION DEVELOPMENT USING PHP",
        marks: 74,
        total: 100,
      },
    ],
    pdfPath: "/results/48.pdf",
  },


];
